import type { Conflict, Hero } from './types';
import { kudusMartyrs } from './data/kudus_martyrs';
import { mehmetcikMartyrs } from './data/mehmetcik_martyrs';

export function isDemoMode(): boolean {
  return !process.env.EXPO_PUBLIC_SUPABASE_URL;
}

export const demoConflicts: Conflict[] = [
  { id: 'd-1', name: 'Çanakkale Savaşı', sort_order: 10 },
  { id: 'd-2', name: 'Sarıkamış Harekatı', sort_order: 20 },
  { id: 'd-3', name: 'Kurtuluş Savaşı', sort_order: 30 },
  { id: 'd-4', name: 'Kore Savaşı', sort_order: 40 },
  { id: 'd-5', name: 'Kıbrıs Barış Harekatı', sort_order: 50 },
  { id: 'd-6', name: '15 Temmuz Darbe Girişimi', sort_order: 60 },
  { id: 'd-7', name: 'Terörle Mücadele', sort_order: 70 },
  { id: 'd-8', name: 'Sınır Ötesi Operasyonlar', sort_order: 80 },
  { id: 'd-9', name: 'Diğer', sort_order: 90 },
  { id: 'd-10', name: 'Birinci Dünya Savaşı', sort_order: 25 },
  { id: 'd-11', name: '93 Harbi', sort_order: 5 },
  { id: 'd-12', name: 'Balkan Savaşları', sort_order: 7 },
  { id: 'd-13', name: 'Muharebe Dışı Şehitler', sort_order: 95 },
  { id: 'd-14', name: 'Görev Şehitleri (2014-2025)', sort_order: 75 },
];

const now = new Date().toISOString();

// Fotoğraflar: Wikimedia Commons üzerinden doğrulanmış (HTTP 200) kamu malı / açık lisanslı URL'ler.
const PHOTOS = {
  seyitOnbasi:
    'https://upload.wikimedia.org/wikipedia/commons/6/6c/Seyit_Onba%C5%9F%C4%B1_%28Harp_Mecmuas%C4%B1%29.jpg',
  ataturk:
    'https://upload.wikimedia.org/wikipedia/commons/1/1e/Kemal_Atat%C3%BCrk_portrait.jpg',
  bigaliMehmet:
    'https://upload.wikimedia.org/wikipedia/commons/9/9d/Bigal%C4%B1_Mehmet_%C3%87avu%C5%9F.jpg',
  esatPasa: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Esad_Pasha.jpg',
  ertugrulAker:
    'https://upload.wikimedia.org/wikipedia/commons/c/cc/Mustafa_Ertugrul.jpg',
  cevatPasa:
    'https://upload.wikimedia.org/wikipedia/commons/9/97/Cevat_%C3%87obanl%C4%B1.jpg',
  halilSami:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Halil_Sami_Bey.jpg/500px-Halil_Sami_Bey.jpg',
  hafizHakki:
    'https://upload.wikimedia.org/wikipedia/commons/e/ed/HAFIZ_HAKKI_PASHA.jpg',
  yorukAli: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Yoruk_Ali_Efe.jpg',
  makbule:
    'https://upload.wikimedia.org/wikipedia/commons/b/b6/G%C3%B6rdesli_Makbule.jpg',
  karaFatma: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Kara_Fatma.jpg',
  karabekir:
    'https://upload.wikimedia.org/wikipedia/commons/9/97/Musa_K%C3%A2z%C4%B1m_Karabekir.jpg',
  cakmak:
    'https://upload.wikimedia.org/wikipedia/commons/d/d1/Mare%C5%9Fal_Fevzi_%C3%87akmak.jpg',
  inonu:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/%C4%B0smet_%C4%B0n%C3%B6n%C3%BC_portresi.jpg/500px-%C4%B0smet_%C4%B0n%C3%B6n%C3%BC_portresi.jpg',
  halideEdip:
    'https://upload.wikimedia.org/wikipedia/commons/e/e8/Halide_Edib_Ad%C4%B1var_b3.jpg',
  hasanTahsin:
    'https://upload.wikimedia.org/wikipedia/commons/2/21/Hasan_Tahsin.jpg',
  halilKut: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Halil_Kut.png',
  tahsinYazici:
    'https://upload.wikimedia.org/wikipedia/commons/7/74/Milburn_Yazici.jpg',
  denktas:
    'https://upload.wikimedia.org/wikipedia/commons/9/92/Rauf_Raif_Denkta%C5%9F.jpg',
  fazilKucuk:
    'https://upload.wikimedia.org/wikipedia/commons/d/de/Image_of_Faz%C4%B1l_K%C3%BC%C3%A7%C3%BCk_in_1963.png',
} as const;

function hero(
  h: Omit<Hero, 'created_at' | 'updated_at' | 'approved_at'> & {
    approved_at?: string | null;
  }
): Hero {
  return {
    ...h,
    approved_at: h.approved_at ?? now,
    created_at: now,
    updated_at: now,
  };
}

export const demoHeroes: Hero[] = [
  // ============================================================
  // ÇANAKKALE SAVAŞI (d-1)
  // ============================================================
  hero({
    id: 'd-h1',
    full_name: 'Seyit Onbaşı (Seyit Ali Çabuk)',
    rank: 'Onbaşı',
    unit: '27. Alay, Ağır Topçu Bataryası',
    birth_date: '1889-09-01',
    birth_place: 'Balıkesir',
    death_date: '1939-11-30',
    death_place: 'Balıkesir',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Çanakkale Savaşı sırasında 215 kilogramlık top mermisini sırtında taşıyarak İngiliz zırhlısı HMS Ocean\'ı vurmasıyla bilinen efsanevi asker.',
    story:
      '18 Mart 1915\'te Rumeli Mecidiye Tabyası\'nda, topun mermi kaldıran vinci isabet sonucu bozulunca 215 kilogramlık mermiyi sırtında taşıyıp topa sürerek HMS Ocean\'ı kıç tarafından vurdu ve zırhlının batmasına yol açtı. Savaştan sonra memleketi Balıkesir\'e dönen Seyit Onbaşı, 1939\'da vefat etti ve vasiyeti üzerine tabyadaki yeri önüne defnedildi.',
    profile_photo_url: PHOTOS.seyitOnbasi,
    grave_location: 'Çanakkale, Rumeli Mecidiye Tabyası',
    lat: 40.058,
    lng: 26.183,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h2',
    full_name: 'Mustafa Kemal Atatürk',
    rank: 'Mareşal',
    unit: 'Türk Silahlı Kuvvetleri Başkomutanı',
    birth_date: '1881-01-01',
    birth_place: 'Selanik',
    death_date: '1938-11-10',
    death_place: 'İstanbul',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kurtuluş Savaşı\'nın önderi, Çanakkale\'de "Size taarruzu değil ölmeyi emrediyorum" sözüyle tarihe geçen Türkiye Cumhuriyeti\'nin kurucusu.',
    story:
      'Çanakkale Savaşı\'nda Anafartalar ve Conkbayırı zaferleriyle savaşın seyrini değiştirdi. "Ben size taarruzu değil, ölmeyi emrediyorum!" emriyle 57. Alay\'a ve tüm Mehmetçik\'e cesaret oldu. Kurtuluş Savaşı\'nı başlatarak Türkiye Cumhuriyeti\'ni kurdu.',
    profile_photo_url: PHOTOS.ataturk,
    grave_location: 'Anıtkabir, Ankara',
    lat: 39.925,
    lng: 32.837,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h3',
    full_name: 'Yahya Çavuş',
    rank: 'Çavuş',
    unit: 'Seddülbahir, 26. Alay',
    birth_date: '1887-01-01',
    birth_place: 'Balıkesir',
    death_date: '1915-04-25',
    death_place: 'Seddülbahir, Çanakkale',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: true,
    is_veteran: false,
    summary:
      '25 Nisan 1915\'te Seddülbahir\'de 10 kişilik mangasıyla bir taburluk Anzak çıkarmasını saatlerce durduran kahraman çavuş.',
    story:
      '25 Nisan 1915 sabahı Seddülbahir kalesinde 10 kişilik ekibiyle düşman çıkarmasına karşı koydu. Ertesi gün şehit olduğunda vücudunda 14 kurşun yarası vardı; fakat o bir gün boyunca Anzak çıkarmasını tek başına durdurmuştu.',
    profile_photo_url: null,
    grave_location: 'Seddülbahir Şehitliği, Çanakkale',
    lat: 40.043,
    lng: 26.159,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h9',
    full_name: 'Bigalı Mehmet Çavuş',
    rank: 'Çavuş',
    unit: '57. Alay, 19. Tümen',
    birth_date: '1894-01-01',
    birth_place: 'Balıkesir, Bigadiç',
    death_date: '1917-06-10',
    death_place: 'Anadolu (hastalık)',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Anafartalar Kahramanı olarak bilinen, 15 Mayıs 1915\'te el bombalarıyla bir İngiliz saldırısını durdurup iki esir alan efsanevi asker.',
    story:
      '15 Mayıs 1915 gecesi Kanlısırt\'ta tek başına siperine yığılan İngiliz askerlerine el bombaları fırlattı, saldırıyı püskürttü ve iki esirle birlikte bağlı bulunduğu bölüğe döndü. Savaşın ardından yakalandığı hastalık sonucu 1917 yılında şehit oldu.',
    profile_photo_url: PHOTOS.bigaliMehmet,
    grave_location: 'Balıkesir, Bigadiç',
    lat: 39.393,
    lng: 28.13,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h10',
    full_name: 'Mustafa Ertuğrul Aker',
    rank: 'Yüzbaşı',
    unit: 'Müstahkem Mevki Komutanlığı, Marmaris',
    birth_date: '1892-01-01',
    birth_place: 'Antalya',
    death_date: '1961-06-18',
    death_place: 'Ankara',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Çanakkale\'de İngiliz denizaltısı E-7\'yi ve üç savaş gemisini torpille batıran, dünyada denizaltı batıran ilk kıyı topçu subayı.',
    story:
      '1915 yılında Kilitbahir\'deki topçu bataryalarına komuta ederken İngiliz denizaltılarını avladı. E-7 denizaltısı başta olmak üzere üç savaş gemisini torpille batırarak tarihe geçti; bu başarısıyla dünyada denizaltı batıran ilk kıyı topçu subayı unvanını kazandı. Savaştan sonra çeşitli kademelerde görev yaparak 1961\'de vefat etti.',
    profile_photo_url: PHOTOS.ertugrulAker,
    grave_location: 'Ankara, Cebeci Askeri Şehitliği',
    lat: 39.929,
    lng: 32.854,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h11',
    full_name: 'Esat Paşa (Mehmet Esat Bülkat)',
    rank: 'Korgeneral',
    unit: '3. Kolordu Komutanı',
    birth_date: '1862-10-18',
    birth_place: 'Yanya',
    death_date: '1952-11-02',
    death_place: 'İstanbul',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Çanakkale\'de Anafartalar ve Arıburnu cephelerini yöneten, 25 Nisan çıkarmasını durduran 3. Kolordu Komutanı.',
    story:
      'Çanakkale Savaşı\'nın en kritik günü olan 25 Nisan 1915\'te 19. Tümen\'i Anzak çıkarması üzerine sevk ederek savaşın seyrini değiştirdi. Tarihçilere göre savaşın "asıl galibi" olarak anılır; Kurtuluş Savaşı\'na katılmadıysa da Çanakkale savunmasındaki rolü büyüktür. 1952\'de İstanbul\'da vefat etti.',
    profile_photo_url: PHOTOS.esatPasa,
    grave_location: 'İstanbul',
    lat: 41.008,
    lng: 28.978,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h12',
    full_name: 'Cevat Paşa (Cevat Çobanlı)',
    rank: 'Orgeneral',
    unit: 'Çanakkale Müstahkem Mevki Komutanı',
    birth_date: '1870-09-14',
    birth_place: 'İstanbul',
    death_date: '1938-03-13',
    death_place: 'İstanbul',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      '18 Mart 1915 deniz zaferinin mimarı; Çanakkale Boğazı\'nı mayınlayarak İtilaf donanmasını durduran komutan.',
    story:
      'Çanakkale Müstahkem Mevki Komutanı olarak boğazı mayın hatlarıyla savundu. 18 Mart 1915\'te İtilaf donanmasının geçme girişimi, yerli yapımı mayınların ve Nusret mayın gemisinin katkısıyla püskürtüldü. Kurtuluş Savaşı\'nda da Batı Cephesi\'nde görev aldı, Genelkurmay Başkanlığı yaptı.',
    profile_photo_url: PHOTOS.cevatPasa,
    grave_location: 'İstanbul, Karacaahmet Mezarlığı',
    lat: 41.011,
    lng: 29.03,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h13',
    full_name: 'Halil Sami Bey',
    rank: 'Albay',
    unit: '26. Tümen Komutanı',
    birth_date: null,
    birth_place: 'İstanbul',
    death_date: null,
    death_place: 'Bursa',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Seddülbahir\'de 25 Nisan 1915 İngiliz çıkarmasını durduran 26. Tümen Komutanı.',
    story:
      '25 Nisan 1915\'te Seddülbahir cephesinde 26. Tümeni ile İngiliz çıkarmasına karşı koydu. Yahya Çavuş\'un kahramanlık destanının yazıldığı bu cephede tümeniyle çıkarmayı durdurmayı başardı. Savaştan sonra çeşitli görevlerde bulundu.',
    profile_photo_url: PHOTOS.halilSami,
    grave_location: 'Bursa',
    lat: 40.183,
    lng: 29.067,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // SARIKAMIŞ HAREKATI (d-2)
  // ============================================================
  hero({
    id: 'd-h14',
    full_name: 'Hafız Hakkı Paşa',
    rank: 'Birinci Ferik (Orgeneral)',
    unit: '10. Kolordu Komutanı',
    birth_date: '1879-04-01',
    birth_place: 'İstanbul',
    death_date: '1915-02-15',
    death_place: 'Erzurum',
    conflict_id: 'd-2',
    conflict: demoConflicts[1],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Sarıkamış Harekatı\'nda 10. Kolordu\'ya komuta eden; harekat sırasında tifüse yakalanıp şehit olan komutan.',
    story:
      'Sarıkamış Harekatı\'nda 10. Kolordu Komutanı olarak görev yaptı. Harekatın zorlu kış koşullarında birliklerinin başından ayrılmadı; bu sırada yakalandığı tifüs hastalığına yenilerek 15 Şubat 1915\'te Erzurum\'da şehit oldu.',
    profile_photo_url: PHOTOS.hafizHakki,
    grave_location: 'Erzurum',
    lat: 39.912,
    lng: 41.254,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h15',
    full_name: 'Binbaşı Agah Bey',
    rank: 'Binbaşı',
    unit: '86. Alay Komutanı',
    birth_date: null,
    birth_place: 'İstanbul',
    death_date: '1914-12-26',
    death_place: 'Sarıkamış',
    conflict_id: 'd-2',
    conflict: demoConflicts[1],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Sarıkamış\'ta 86. Alayı ile düşman ateşi altında ilerlerken 26 Aralık 1914\'te şehit olan alay komutanı.',
    story:
      'Sarıkamış Harekatı sırasında 86. Alay\'ın başında dondurucu soğukta ilerledi. 26 Aralık 1914\'te düşman ateşi sonucu şehit oldu; ölümünden sonra 86. Alayın komutanlığını Binbaşı Sabit Bey devraldı.',
    profile_photo_url: null,
    grave_location: 'Sarıkamış',
    lat: 40.335,
    lng: 42.574,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h16',
    full_name: 'Binbaşı Sabit Bey',
    rank: 'Binbaşı',
    unit: '85. Alay Komutanı',
    birth_date: null,
    birth_place: 'İstanbul',
    death_date: '1914-12-27',
    death_place: 'Sarıkamış',
    conflict_id: 'd-2',
    conflict: demoConflicts[1],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Sarıkamış\'ta 85. Alayı ile taarruz ederken 27 Aralık 1914\'te şehit olan komutan.',
    story:
      'Sarıkamış Harekatı\'nda 85. Alay Komutanı olarak düşman mevzilerine taarruz etti. 27 Aralık 1914 günü çatışmalar sırasında şehit oldu; şehadeti harekatın en kanlı günlerine tanıklık etti.',
    profile_photo_url: null,
    grave_location: 'Sarıkamış',
    lat: 40.335,
    lng: 42.574,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // KURTULUŞ SAVAŞI (d-3)
  // ============================================================
  hero({
    id: 'd-h4',
    full_name: 'Şerife Bacı',
    rank: null,
    unit: 'Cephe Gerisi Hizmeti',
    birth_date: '1900-01-01',
    birth_place: 'Kastamonu',
    death_date: '1921-01-01',
    death_place: 'Kastamonu',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Kurtuluş Savaşı\'nda cephane taşırken dondurucu soğukta şehit olan kahraman Türk kadını.',
    story:
      'İnebolu\'dan cepheye cephane taşıyan kağnı kafilesinde kundağındaki bebeğiyle yola çıkan Şerife Bacı, yağmur ve kar altında cephaneyi ıslanmasın diye üstündeki örtüyle örttü. Sabaha karşı donmuş bedeni ve yanında bebeği bulundu; cephane sağlam olarak cepheye ulaşmıştı.',
    profile_photo_url: null,
    grave_location: 'Kastamonu Şehitliği',
    lat: 41.376,
    lng: 33.778,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h17',
    full_name: 'Yörük Ali Efe',
    rank: null,
    unit: 'Milli Aydın Cephesi Komutanı',
    birth_date: '1886-01-01',
    birth_place: 'Aydın',
    death_date: '1951-09-23',
    death_place: 'Bursa',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Aydın\'ın işgalinde Malgaç Baskını ile düşmana ilk darbeyi vuran, "Milli Aydın Cephesi" komutanı efe.',
    story:
      'Yunan işgaline karşı Aydın yöresinde milis güçlerini örgütledi. 16 Haziran 1919\'da düzenlediği Malgaç Baskını ile düşmana ilk büyük darbeyi vurdu ve bölge halkının direnişinin sembolü oldu. Savaş sonrası İstiklal Madalyası ile ödüllendirildi; 1951\'de Bursa\'da vefat etti.',
    profile_photo_url: PHOTOS.yorukAli,
    grave_location: 'Bursa',
    lat: 40.183,
    lng: 29.067,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h18',
    full_name: 'Gördesli Makbule',
    rank: null,
    unit: 'Demirci Akıncıları',
    birth_date: '1902-01-01',
    birth_place: 'Manisa, Gördes',
    death_date: '1922-03-17',
    death_place: 'Manisa, Gördes',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Eşinin yanında Yunan kuvvetlerine karşı savaşan, 1922\'de Kılbasan mevkiinde şehit olan genç kadın kahraman.',
    story:
      'Yunan işgaline karşı Demirci Akıncıları\'na katılarak eşiyle birlikte cephede savaştı. 17 Mart 1922\'de Gördes yakınlarındaki Kılbasan mevkiinde düşmanla çatışırken şehit oldu; fedakarlığı Kurtuluş Savaşı\'nın sembollerinden oldu.',
    profile_photo_url: PHOTOS.makbule,
    grave_location: 'Manisa, Gördes',
    lat: 38.934,
    lng: 28.295,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h19',
    full_name: 'Kara Fatma (Fatma Seher Erden)',
    rank: null,
    unit: 'Milli Mücadele Müfrezeleri',
    birth_date: '1888-01-01',
    birth_place: 'Erzurum',
    death_date: '1955-07-02',
    death_place: 'İstanbul',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kurtuluş Savaşı\'nda kadınlardan oluşan milis müfrezeleri kuran, savaşta büyük yararlılık gösteren "Kara Fatma".',
    story:
      'Birinci Dünya Savaşı\'nda Kafkas Cephesi\'nde eşiyle savaştı; eşinin şehadetinden sonra Mustafa Kemal Paşa\'nın yanında Kurtuluş Savaşı\'na katıldı. Batı Cephesi\'nde keşif ve baskın görevlerinde büyük yararlılık gösterdi, İstiklal Madalyası kazandı. 1955\'te İstanbul\'da vefat etti.',
    profile_photo_url: PHOTOS.karaFatma,
    grave_location: 'İstanbul, Karacaahmet Mezarlığı',
    lat: 41.011,
    lng: 29.03,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h20',
    full_name: 'Kazım Karabekir',
    rank: 'Orgeneral',
    unit: '15. Kolordu Komutanı',
    birth_date: '1882-07-23',
    birth_place: 'İstanbul',
    death_date: '1948-01-26',
    death_place: 'Ankara',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Doğu Cephesi Komutanı; Ermeni ordusunu yenerek Sarıkamış, Kars ve Ardahan\'ı kurtaran, "Şark\'ın Fatihi" lakabıyla anılan kumandan.',
    story:
      'Kurtuluş Savaşı\'nda 15. Kolordu ile Doğu Cephesi\'nde Büyük Taarruz\'u gerçekleştirdi; 30 Eylül 1920\'de Sarıkamış, 30 Ekim\'de Kars, 6 Kasım\'da Ardahan düşman işgalinden kurtarıldı. Ordusuyla yetim kalan binlerce çocuğu himaye etti. 1948\'de Ankara\'da vefat etti.',
    profile_photo_url: PHOTOS.karabekir,
    grave_location: 'Ankara, Devlet Mezarlığı',
    lat: 39.933,
    lng: 32.856,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h21',
    full_name: 'Fevzi Çakmak',
    rank: 'Mareşal',
    unit: 'Genelkurmay Başkanı',
    birth_date: '1876-01-12',
    birth_place: 'İstanbul',
    death_date: '1950-04-10',
    death_place: 'İstanbul',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kurtuluş Savaşı\'nın başkomutanlık savaşlarına ve Büyük Taarruz\'a komuta eden Türkiye\'nin ikinci ve son mareşali.',
    story:
      'Sakarya Meydan Muharebesi\'nden Büyük Taarruz\'a kadar tüm kritik harekatlarda Genelkurmay Başkanı olarak görev yaptı. Mustafa Kemal Atatürk ile birlikte "Mareşal" rütbesi ve "Gazi" unvanıyla onurlandırıldı. 1950\'de İstanbul\'da vefat etti.',
    profile_photo_url: PHOTOS.cakmak,
    grave_location: 'İstanbul, Eyüp Sultan',
    lat: 41.047,
    lng: 28.934,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h22',
    full_name: 'İsmet İnönü',
    rank: 'Orgeneral',
    unit: 'Batı Cephesi Komutanı',
    birth_date: '1884-09-24',
    birth_place: 'İzmir',
    death_date: '1973-12-25',
    death_place: 'Ankara',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Birinci ve İkinci İnönü Zaferleri\'nin kahramanı; Lozan\'da Türkiye\'yi temsil eden asker ve devlet adamı.',
    story:
      'Batı Cephesi Komutanı olarak Ocak ve Mart 1921\'de kazandığı İnönü Zaferleri ile Yunan ilerleyişini durdurdu. Lozan Konferansı\'nda başdelege olarak Türkiye Cumhuriyeti\'nin bağımsızlığını tescilledi. 1973\'te Ankara\'da vefat etti.',
    profile_photo_url: PHOTOS.inonu,
    grave_location: 'Anıtkabir, Ankara',
    lat: 39.925,
    lng: 32.837,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h23',
    full_name: 'Halide Edip Adıvar',
    rank: null,
    unit: 'Cephe ve Cephe Gerisi Görevleri',
    birth_date: '1884-01-01',
    birth_place: 'İstanbul',
    death_date: '1964-01-09',
    death_place: 'İstanbul',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Sultanahmet mitinglerindeki ateşli konuşmaları ve Anadolu\'daki cephe görevleriyle Kurtuluş Savaşı\'na hizmet eden yazar.',
    story:
      'İstanbul\'un işgaline karşı 1919 Sultanahmet mitinglerinde halkı direnişe çağırdı. Anadolu\'ya geçerek cephede çavuş, onbaşı rütbeleriyle görev aldı; İzmir\'e giren ilk Türk ordusunda çavuş olarak bulundu. "Ateşten Gömlek" romanıyla Milli Mücadele\'yi edebiyata taşıdı.',
    profile_photo_url: PHOTOS.halideEdip,
    grave_location: 'İstanbul, Aşiyan Mezarlığı',
    lat: 41.083,
    lng: 29.053,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h24',
    full_name: 'Hasan Tahsin (Osman Nevres)',
    rank: null,
    unit: 'İzmir Gazetecisi',
    birth_date: '1888-01-01',
    birth_place: 'Selanik',
    death_date: '1919-05-15',
    death_place: 'İzmir',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Mayıs 1919\'da İzmir\'e çıkan Yunan askerine ilk kurşunu sıkarak Milli Mücadele\'yi başlatan gazeteci.',
    story:
      'İzmir\'in işgal edildiği 15 Mayıs 1919 sabahı, Konak\'ta işgalci Yunan askerlerine ilk kurşunu sıktı ve aynı gün şehit edildi. Attığı bu ilk kurşun, Türk Milli Mücadelesi\'nin başlangıcı kabul edilir.',
    profile_photo_url: PHOTOS.hasanTahsin,
    grave_location: 'İzmir, Konak',
    lat: 38.419,
    lng: 27.129,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h25',
    full_name: 'Sütçü İmam',
    rank: null,
    unit: 'Milli Mücadele Gönüllüsü',
    birth_date: '1871-01-01',
    birth_place: 'Kahramanmaraş',
    death_date: '1922-11-25',
    death_place: 'Kahramanmaraş',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      '31 Ekim 1919\'da Fransız işgaline karşı ilk kurşunu atarak Maraş direnişini başlatan kahraman.',
    story:
      'Fransız işgal kuvvetlerinin Müslüman kadınlara saldırdığı olay üzerine 31 Ekim 1919\'da sütçülük yaptığı gün düşmana ilk kurşunu sıktı. Bu olay Maraş\'ın kurtuluş mücadelesinin fitilini ateşledi; Kurtuluş\'tan sonra onuruna "Sütçü İmam" denildi. 1922\'de vefat etti.',
    profile_photo_url: null,
    grave_location: 'Kahramanmaraş, Sütçü İmam Anıt Mezarı',
    lat: 37.585,
    lng: 36.937,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h26',
    full_name: 'Şahin Bey',
    rank: null,
    unit: 'Antep Kuvayımilliye Komutanı',
    birth_date: '1883-01-01',
    birth_place: 'Gaziantep',
    death_date: '1920-03-28',
    death_place: 'Gaziantep',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Fransız işgaline karşı Antep savunmasında Elmalı Köprüsü\'nde şehit olan Kuvayımilliye komutanı.',
    story:
      'Fransız işgaline karşı Antep\'te Kuvayımilliye kuvvetlerinin komutanlığını yaptı. 28 Mart 1920\'de Elmalı Köprüsü\'nü savunurken vurularak şehit oldu; şehadeti Antep halkının direniş azmini daha da güçlendirdi.',
    profile_photo_url: null,
    grave_location: 'Gaziantep, Şahinbey Şehitliği',
    lat: 37.066,
    lng: 37.383,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h45',
    full_name: 'Demirci Mehmet Efe',
    rank: null,
    unit: 'Aydın Cephesi Kuvayımilliye Komutanı',
    birth_date: '1883-01-01',
    birth_place: 'Aydın, Nazilli',
    death_date: '1961-02-05',
    death_place: 'Aydın',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'İzmir\'in işgalinden sonra Aydın cephesinde Yunan kuvvetlerine karşı mücadele eden Kuvayımilliye komutanı.',
    story:
      'Nazilli yakınlarında doğan Demirci Mehmet Efe, İzmir\'in işgalinin ardından Yunan ilerleyişine karşı Aydın civarında Kuvayımilliye kuvvetleri kurdu ve bölgedeki direnişin komutanlığını üstlendi. Düzensiz kuvvetlerin düzenli orduya dönüştürülmesi sürecinde yaşanan anlaşmazlıkların ardından affedilerek Nazilli\'ye yerleşti; 5 Şubat 1961\'de vefat etti.',
    profile_photo_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Demirci_Mehmet_Efe%2C_1919.webp',
    grave_location: 'Aydın, Nazilli Eğriboyun Mezarlığı',
    lat: 37.91,
    lng: 28.33,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h46',
    full_name: 'Çete Emir Ayşe',
    rank: null,
    unit: 'Kuvayımilliye Gönüllüsü',
    birth_date: '1894-01-01',
    birth_place: 'Aydın, Efeler',
    death_date: '1967-01-01',
    death_place: 'Aydın, Efeler',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Yunan işgaline karşı silaha sarılan, İstiklal Madalyası ile onurlandırılan Milli Mücadele kadın kahramanı.',
    story:
      'Eşini Çanakkale\'de şehit verdikten sonra Aydın\'ın işgalinde silaha sarıldı, efe kıyafetiyle Kuvayımilliye saflarına katıldı. Malgaç Baskını\'nda gösterdiği yararlılıklarla tanındı; 1933 yılında Aydın\'da Atatürk\'ün elinden İstiklal Madalyası aldı. "Bazı kadınların içinde bir pehlivan; bazı erkeklerin içinde de korkaklıklarından dolayı bir kadın gizlidir" sözüyle anılır.',
    profile_photo_url: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Emir_Ay%C5%9Fe_Efe.jpg',
    grave_location: 'Aydın, Efeler İmamköy',
    lat: 37.845,
    lng: 27.83,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // KORE SAVAŞI (d-4)
  // ============================================================
  hero({
    id: 'd-h27',
    full_name: 'Tahsin Yazıcı',
    rank: 'Tuğgeneral',
    unit: 'Kore Türk Silahlı Kuvvetleri Komutanı',
    birth_date: '1892-01-01',
    birth_place: 'Manastır',
    death_date: '1971-02-11',
    death_place: 'Ankara',
    conflict_id: 'd-4',
    conflict: demoConflicts[3],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kore Savaşı\'nda 5 bin kişilik Türk Tugayı\'na komuta eden; Kunuri Muharebesi\'nde kuşatmayı yarıp birliklerini kurtaran komutan.',
    story:
      '1950\'de tuğgeneral rütbesiyle Kore\'ye giden Türk Tugayı\'nın komutanı oldu. Kunuri Muharebesi\'nde düşmanla çevrili tugayını gece yarısı büyük bir kahramanlıkla kuşatmadan çıkardı ve ABD birliklerinin imha edilmesini engelledi. Savaş sırasında tümgeneralliğe yükseldi; 1971\'de Ankara\'da vefat etti.',
    profile_photo_url: PHOTOS.tahsinYazici,
    grave_location: 'Ankara, Cebeci Asri Mezarlığı',
    lat: 39.929,
    lng: 32.854,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h28',
    full_name: 'Miktat Uluünlü',
    rank: 'Binbaşı',
    unit: 'Kore Türk Tugayı, 2. Tabur Komutanı',
    birth_date: null,
    birth_place: null,
    death_date: '1951-05-18',
    death_place: 'Kore',
    conflict_id: 'd-4',
    conflict: demoConflicts[3],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Kunuri ve Kumyangjang-ni muharebelerinde büyük kahramanlık gösteren; 1951\'de şehit olan Türk Tugayı tabur komutanı.',
    story:
      'Kore Savaşı\'nda Türk Tugayı 2. Tabur Komutanı olarak Kunuri Muharebesi\'nde gösterdiği üstün cesaretle "Kunuri\'nin eşsiz kahramanı" olarak anıldı ve Silver Star madalyası aldı. 18 Mayıs 1951\'de Kumyangjang-ni bölgesinde şehit oldu.',
    profile_photo_url: null,
    grave_location: 'Seul, Pusan Şehitliği',
    lat: 35.179,
    lng: 129.076,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // KIBRIS BARIŞ HAREKATI (d-5)
  // ============================================================
  hero({
    id: 'd-h29',
    full_name: 'İbrahim Karaoğlanoğlu',
    rank: 'Albay',
    unit: '39. Piyade Tümeni, 50. Alay Komutanı',
    birth_date: '1922-07-01',
    birth_place: 'Ankara',
    death_date: '1974-07-21',
    death_place: 'Girne, Kıbrıs',
    conflict_id: 'd-5',
    conflict: demoConflicts[4],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Kıbrıs Barış Harekatı\'nda Girne\'de çıkarma birliklerine komuta eden, 21 Temmuz 1974\'te şehit olan kahraman albay.',
    story:
      '20 Temmuz 1974\'te Kıbrıs Barış Harekatı\'nın ilk günü Girne\'de deniz çıkarmasını yöneten birliklere komuta etti. Girne Boğazı\'ndaki çatışmalarda 21 Temmuz\'da şehit oldu; adı Girne\'deki 50. Piyade Alayı kışlasına verildi.',
    profile_photo_url: null,
    grave_location: 'Ankara, Cebeci Askeri Şehitliği',
    lat: 39.929,
    lng: 32.854,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h30',
    full_name: 'Cengiz Topel',
    rank: 'Yüzbaşı (Pilot)',
    unit: 'Hava Kuvvetleri Komutanlığı',
    birth_date: '1934-09-02',
    birth_place: 'İstanbul',
    death_date: '1964-08-08',
    death_place: 'Lefke, Kıbrıs',
    conflict_id: 'd-5',
    conflict: demoConflicts[4],
    is_martyr: true,
    is_veteran: false,
    summary:
      '1964 Erenköy direnişine destek uçuşları yaparken uçağı düşürülen ve şehit edilen ilk Türk Hava Kuvvetleri pilotu.',
    story:
      '8 Ağustos 1964\'te Erenköy\'deki Kıbrıslı Türk direnişçilere destek için keşif uçuşu yaparken uçağı Rumlar tarafından vuruldu. Atıldığı esaret sırasında şehit edildi; Türk Hava Kuvvetleri\'nin ilk hava şehidi olarak tarihe geçti.',
    profile_photo_url: null,
    grave_location: 'İstanbul, Zincirlikuyu Askeri Şehitliği',
    lat: 41.074,
    lng: 29.012,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h31',
    full_name: 'Rauf Denktaş',
    rank: null,
    unit: 'Kıbrıs Türk Federe Devleti Kurucusu',
    birth_date: '1924-01-27',
    birth_place: 'Baf, Kıbrıs',
    death_date: '2012-01-13',
    death_place: 'Lefkoşa, KKTC',
    conflict_id: 'd-5',
    conflict: demoConflicts[4],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kıbrıs Türk halkının varoluş mücadelesinin önderi, Kuzey Kıbrıs Türk Cumhuriyeti\'nin kurucu cumhurbaşkanı.',
    story:
      '1955\'ten itibaren Kıbrıs Türk toplumunun siyasi liderliğini üstlendi; EOKA saldırılarına karşı halkın haklarını savundu. 1974 Barış Harekatı sonrası kurulan Kıbrıs Türk Federe Devleti ve ardından KKTC\'nin kuruluşunda baş rolü oynadı. 2012\'de Lefkoşa\'da vefat etti.',
    profile_photo_url: PHOTOS.denktas,
    grave_location: 'Lefkoşa, Cumhuriyet Parkı',
    lat: 35.185,
    lng: 33.382,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h32',
    full_name: 'Fazıl Küçük',
    rank: null,
    unit: 'Kıbrıs Türk toplumunun lideri',
    birth_date: '1906-03-14',
    birth_place: 'Lefkoşa, Kıbrıs',
    death_date: '1984-01-15',
    death_place: 'Londra',
    conflict_id: 'd-5',
    conflict: demoConflicts[4],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kıbrıs Türk halkının haklarını dünya kamuoyuna duyuran, Kıbrıs Türk toplumunun ilk cumhurbaşkanı yardımcısı.',
    story:
      '1955\'te kurduğu Kıbrıs Türktür Partisi ile Rumların Enosis emellerine karşı mücadele etti. 1959 Zürih ve Londra Antlaşmaları sonrası Kıbrıs Cumhuriyeti\'nin kurucu cumhurbaşkanı yardımcısı oldu; 1963 Kanlı Noel saldırılarında halkın örgütlenmesinde büyük rol oynadı.',
    profile_photo_url: PHOTOS.fazilKucuk,
    grave_location: 'Lefkoşa, Dr. Fazıl Küçük Anıt Mezarı',
    lat: 35.185,
    lng: 33.382,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h33',
    full_name: 'Nihat İlhan',
    rank: 'Tabip Binbaşı',
    unit: 'Kıbrıs Türk Kuvvetleri Alayı',
    birth_date: '1924-06-07',
    birth_place: 'Elazığ',
    death_date: '2016-11-23',
    death_place: 'Ankara',
    conflict_id: 'd-5',
    conflict: demoConflicts[4],
    is_martyr: false,
    is_veteran: true,
    summary:
      '1963 Kanlı Noel\'de eşi ve üç oğlu şehit edilen; "vatan sağolsun" diyerek mücadeleye devam eden tabip.',
    story:
      'Kıbrıs Türk Kuvvetleri Alayı\'nın baştabibi olarak görev yaparken 24 Aralık 1963 gecesi, Lefkoşa\'daki evini basan Rum çeteleri eşi Mürüvvet ile üç oğlu Murat, Kutsi ve Hakan\'ı şehit etti. Haberi aldığında yalnızca "Vatan sağolsun" dedi; hayatını kimsesiz çocuklara adadı. 2016\'da vefat etti.',
    profile_photo_url: null,
    grave_location: 'Elazığ, İcadiye Askeri Şehitliği',
    lat: 38.674,
    lng: 39.223,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // 15 TEMMUZ DARBE GİRİŞİMİ (d-6)
  // ============================================================
  hero({
    id: 'd-h6',
    full_name: 'Ömer Halisdemir',
    rank: 'Piyade Astsubay Kıdemli Başçavuş',
    unit: 'Özel Kuvvetler Komutanlığı',
    birth_date: '1974-02-10',
    birth_place: 'Niğde',
    death_date: '2016-07-16',
    death_place: 'Ankara',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz darbe girişiminde darbeci generali vurarak Özel Kuvvetler Komutanlığının ele geçirilmesini engelleyen, ardından şehit edilen kahraman asker.',
    story:
      '15 Temmuz 2016 gecesi darbeci general Semih Terzi\'nin komutanlığı ele geçirmeye çalıştığı sırada, milletinin emriyle hareket ederek Terzi\'yi etkisiz hale getirdi. Bu fedakarlığı Özel Kuvvetler Komutanlığının darbecilerin eline geçmesini engelledi. Hemen ardından şehit edildi. Kabri, şehadetinin yıldönümlerinde binlerce vatandaş tarafından ziyaret edilmektedir.',
    profile_photo_url: null,
    grave_location: 'Niğde, Merkez Mezarlığı',
    lat: 37.969,
    lng: 34.678,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h34',
    full_name: 'Erol Olçok',
    rank: null,
    unit: '15 Temmuz Demokrasi Şehidi',
    birth_date: '1962-04-14',
    birth_place: 'Çorum, Osmancık',
    death_date: '2016-07-16',
    death_place: 'İstanbul',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz gecesi oğlu Tayyip ile birlikte Boğaz Köprüsü\'nde darbecilere karşı direnirken şehit olan reklamcı.',
    story:
      '15 Temmuz 2016 gecesi oğlu Abdullah Tayyip Olçok ile birlikte darbe girişimine karşı Boğaz Köprüsü\'nde halkın önünde durdu. Darbecilerin açtığı ateş sonucu oğluyla birlikte şehit oldu; aynı anda iki evladını kaybeden ailesi Türkiye\'nin acısını simgeledi.',
    profile_photo_url: null,
    grave_location: 'İstanbul, Edirnekapı Şehitliği',
    lat: 41.029,
    lng: 28.936,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h35',
    full_name: 'Abdullah Tayyip Olçok',
    rank: null,
    unit: '15 Temmuz Demokrasi Şehidi',
    birth_date: '1999-01-01',
    birth_place: 'İstanbul',
    death_date: '2016-07-16',
    death_place: 'İstanbul',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz gecesi babası Erol Olçok ile Boğaz Köprüsü\'nde darbecilere karşı dururken şehit olan 17 yaşındaki genç.',
    story:
      'Babası Erol Olçok ile birlikte 15 Temmuz gecesi Boğaz Köprüsü\'nde milletin safında yer aldı. Darbeci askerlerin açtığı ateş sonucu babasıyla birlikte şehit oldu; 15 Temmuz\'un en genç şehitlerinden biri olarak tarihe geçti.',
    profile_photo_url: null,
    grave_location: 'İstanbul, Edirnekapı Şehitliği',
    lat: 41.029,
    lng: 28.936,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h36',
    full_name: 'Mustafa Cambaz',
    rank: null,
    unit: 'Yeni Şafak Gazetesi Foto Muhabiri',
    birth_date: '1962-01-01',
    birth_place: 'Kayseri',
    death_date: '2016-07-16',
    death_place: 'İstanbul',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz gecesi Boğaz Köprüsü\'nde şehitleri fotoğraflarken darbecilerin kurşunuyla şehit olan foto muhabiri.',
    story:
      '15 Temmuz 2016 gecesi Boğaz Köprüsü\'nde darbecilere karşı direnen halkın fotoğraflarını çekerken vurularak şehit oldu. Elindeki makinesiyle ölümsüz kareler bırakan Cambaz, "kalemi ve kamerayla şehit olan" ilk gazeteci olarak anıldı.',
    profile_photo_url: null,
    grave_location: 'Kayseri',
    lat: 38.731,
    lng: 35.479,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h37',
    full_name: 'Halil İbrahim Yıldırım',
    rank: null,
    unit: '15 Temmuz Demokrasi Şehidi',
    birth_date: '2001-01-01',
    birth_place: 'Kahramanmaraş',
    death_date: '2016-07-16',
    death_place: 'İstanbul',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz\'da Boğaz Köprüsü\'nde şehit olan, 15 yaşındaki en genç demokrasi şehidi.',
    story:
      '15 Temmuz 2016 gecesi babasıyla birlikte Boğaz Köprüsü\'ne koşan 15 yaşındaki Halil İbrahim, darbecilerin tank ateşi altında şehit oldu. Türkiye\'nin en genç 15 Temmuz şehidi olarak hafızalara kazındı.',
    profile_photo_url: null,
    grave_location: 'Kahramanmaraş, Şehitler Mezarlığı',
    lat: 37.585,
    lng: 36.937,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h38',
    full_name: 'İlhan Varank',
    rank: null,
    unit: '15 Temmuz Demokrasi Şehidi',
    birth_date: '1975-04-15',
    birth_place: 'Kayseri',
    death_date: '2016-07-16',
    death_place: 'Ankara',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz gecesi Akıncı Üssü önünde darbecilere karşı direnirken şehit olan mühendis.',
    story:
      '15 Temmuz 2016 gecesi darbecilerin üssü olan Akıncı Üssü önünde halkın direnişinde yer aldı. Darbecilerin açtığı ateş sonucu şehit oldu; aziz hatırası 15 Temmuz kahramanları arasında yaşatılmaktadır.',
    profile_photo_url: null,
    grave_location: 'Kayseri',
    lat: 38.731,
    lng: 35.479,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h39',
    full_name: 'Sait Ertürk',
    rank: 'Polis Memuru',
    unit: 'Ankara Emniyet Müdürlüğü',
    birth_date: '1958-01-01',
    birth_place: 'Sivas',
    death_date: '2016-07-16',
    death_place: 'Ankara',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz gecesi Akıncı Üssü önünde görev yaparken darbecilerce şehit edilen polis memuru.',
    story:
      '15 Temmuz 2016 gecesi Ankara Akıncı Üssü önünde görev yapan Sait Ertürk, darbeci askerlerin silahlı saldırısı sonucu şehit oldu. 15 Temmuz gecesi görevi başında şehit olan polislerimizdendir.',
    profile_photo_url: null,
    grave_location: 'Sivas',
    lat: 39.748,
    lng: 37.015,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // TERÖRLE MÜCADELE (d-7)
  // ============================================================
  hero({
    id: 'd-h7',
    full_name: 'Emin Çakıroğlu',
    rank: 'Piyade Teğmen',
    unit: 'Özel Harp Dairesi',
    birth_date: '1979-05-01',
    birth_place: 'İstanbul',
    death_date: '2000-07-25',
    death_place: 'Kırklareli',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Devletin içine sızmış olan ihanet şebekesine karşı mücadele ederken 25 Temmuz 2000 gecesi şehit edilen istihbarat subayı.',
    story:
      'Atatürkçülüğe ve milletine sadık bir istihbarat subayı olarak vatan hainlerinin planlarını devlete aktardığı için 2000 yılında şehit edildi. Davası 2022\'de sonuçlandı; aziz hatırası Türk milletinin gönlünde yaşamaktadır.',
    profile_photo_url: null,
    grave_location: 'İstanbul',
    lat: 41.008,
    lng: 28.978,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h8',
    full_name: 'Fethi Sekin',
    rank: 'Komiser Yardımcısı',
    unit: 'İzmir Emniyet Müdürlüğü',
    birth_date: '1962-01-01',
    birth_place: 'Iğdır',
    death_date: '2017-01-05',
    death_place: 'İzmir',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      '5 Ocak 2017\'de İzmir Adliyesi önünde terör saldırısını, silah arkadaşı Musa Can ile birlikte kendi canını feda ederek engelleyen kahraman polis.',
    story:
      '5 Ocak 2017 sabahı İzmir Adliyesi önünde kendini patlatmak üzere olan teröristleri, yanında tek silah arkadaşı Musa Can ile birlikte karşıladı. Göğüs göğüse çatışmada teröristleri etkisiz hale getirdi ve olası yüzlerce canı kurtardı; çatışmada şehit oldu. Silah arkadaşı Komiser Musa Can da şehitler kervanına katıldı.',
    profile_photo_url: null,
    grave_location: 'Iğdır, Ağrıdağı Şehitliği',
    lat: 39.888,
    lng: 44.033,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h40',
    full_name: 'Musa Can',
    rank: 'Komiser',
    unit: 'İzmir Emniyet Müdürlüğü',
    birth_date: '1979-01-01',
    birth_place: 'İstanbul',
    death_date: '2017-01-05',
    death_place: 'İzmir',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      '5 Ocak 2017\'de İzmir Adliyesi terör saldırısında, silah arkadaşı Fethi Sekin ile birlikte yüzlerce canı kurtarırken şehit olan polis.',
    story:
      '5 Ocak 2017 sabahı İzmir Adliyesi önünde terör saldırısını fark ettiğinde silah arkadaşı Komiser Yardımcısı Fethi Sekin ile birlikte teröristlerin üzerine gitti. Çatışmada birlikte şehit oldular; fedakarlıkları olası bir katliamı engelledi.',
    profile_photo_url: null,
    grave_location: 'İstanbul',
    lat: 41.008,
    lng: 28.978,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h41',
    full_name: 'Eren Bülbül',
    rank: null,
    unit: 'Jandarma Gönüllüsü',
    birth_date: '2002-01-01',
    birth_place: 'Trabzon, Maçka',
    death_date: '2017-08-11',
    death_place: 'Trabzon, Maçka',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Teröristlerin yerini gösterirken 11 Ağustos 2017\'de şehit edilen 15 yaşındaki çocuk.',
    story:
      'Trabzon Maçka\'da dağda gördüğü teröristleri güvenlik güçlerine bildirdi. Jandarma ekipleriyle birlikte teröristleri takip ederken teröristlerin açtığı ateş sonucu 11 Ağustos 2017\'de şehit oldu. Cenazesinde "Vatan sağolsun" yazılı Türk bayrağı taşınan Eren, Türkiye\'nin yüreğine kazındı.',
    profile_photo_url: null,
    grave_location: 'Trabzon, Maçka',
    lat: 40.81,
    lng: 39.615,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h42',
    full_name: 'Gaffar Okkan',
    rank: '1. Sınıf Emniyet Müdürü',
    unit: 'Diyarbakır Emniyet Müdürlüğü',
    birth_date: '1952-01-01',
    birth_place: 'Sakarya, Hendek',
    death_date: '2001-01-24',
    death_place: 'Diyarbakır',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Diyarbakır halkının gönlünde taht kuran, 24 Ocak 2001\'de silahlı saldırıda şehit edilen emniyet müdürü.',
    story:
      '1997\'de atandığı Diyarbakır\'da terörle mücadelenin yanı sıra halkla kurduğu sıcak ilişkilerle bilindi. 24 Ocak 2001\'de makam aracıyla seyir halindeyken uğradığı silahlı saldırıda şehit oldu; kendisiyle birlikte 6 kişi hayatını kaybetti.',
    profile_photo_url: null,
    grave_location: 'Sakarya, Hendek',
    lat: 40.798,
    lng: 30.748,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h44',
    full_name: 'Mahmut Yıldırım (Yeşil)',
    rank: null,
    unit: 'İstihbarat Görevlisi',
    birth_date: '1953-05-03',
    birth_place: 'Bingöl, Solhan',
    death_date: null,
    death_place: null,
    conflict_id: 'd-9',
    conflict: demoConflicts[8],
    is_martyr: false,
    is_veteran: false,
    summary:
      '"Yeşil" kod adıyla bilinen tartışmalı istihbarat görevlisi; Susurluk soruşturmasında adı geçti, 1996\'dan beri kendisinden haber alınamadı.',
    story:
      '3 Mayıs 1953\'te Bingöl\'ün Solhan ilçesinde doğdu. 1974 Kıbrıs Barış Harekâtı\'na katıldı, sonrasında istihbarat birimlerinde görev yaptığı öne sürüldü. 3 Kasım 1996\'daki Susurluk kazasıyla ortaya çıkan devlet-mafya ilişkilerinde "Yeşil" adı pek çok olayla birlikte anıldı; hakkındaki iddialar mahkemelerde ve basında yıllarca tartışıldı. Kasım 1996\'da Şam\'da görüldüğüne dair haberlerin ardından kendisinden bir daha haber alınamadı; akıbeti hâlâ bilinmiyor.',
    profile_photo_url: null,
    grave_location: null,
    lat: 38.883,
    lng: 40.47,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h43',
    full_name: 'Burak Çam',
    rank: 'Uzman Çavuş',
    unit: 'Özel Harekat',
    birth_date: null,
    birth_place: null,
    death_date: '2017-03-01',
    death_place: 'Şırnak, Cizre',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Cizre\'de terör örgütüyle çatışmada "Kara Astsubay" lakabıyla anılan şehit özel harekatçı.',
    story:
      'Cizre\'de terör örgütü üyeleriyle girdiği çatışmada ağır yaralandı ve şehit oldu. Cesareti ve fedakarlığıyla silah arkadaşlarının gönlünde "Kara Astsubay" olarak anıldı; şehadeti terörle mücadele şehitlerimizin sembol isimlerinden biri oldu.',
    profile_photo_url: null,
    grave_location: 'Şırnak, Cizre',
    lat: 37.323,
    lng: 42.191,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // SINIR ÖTESİ OPERASYONLAR (d-8)
  // ============================================================
  hero({
    id: 'd-h44',
    full_name: 'Ercan Çelik',
    rank: 'Uzman Çavuş',
    unit: 'Fırat Kalkanı Harekatı',
    birth_date: '1990-01-01',
    birth_place: 'Aksaray',
    death_date: '2016-08-24',
    death_place: 'Cerablus, Suriye',
    conflict_id: 'd-8',
    conflict: demoConflicts[7],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Fırat Kalkanı Harekatı\'nın ilk şehidi; 24 Ağustos 2016\'da Cerablus\'ta şehit olan kahraman asker.',
    story:
      '24 Ağustos 2016\'da başlayan Fırat Kalkanı Harekatı\'nda Cerablus bölgesindeki çatışmalarda şehit oldu. Harekatın ilk şehidi olan Ercan Çelik, sınır ötesi operasyonlarımızın kahramanlık destanını başlattı.',
    profile_photo_url: null,
    grave_location: 'Aksaray',
    lat: 38.371,
    lng: 34.03,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h45',
    full_name: 'Musa Özalkan',
    rank: 'Astsubay Üstçavuş',
    unit: 'Zeytin Dalı Harekatı',
    birth_date: '1988-01-01',
    birth_place: 'Kastamonu',
    death_date: '2018-01-20',
    death_place: 'Afrin, Suriye',
    conflict_id: 'd-8',
    conflict: demoConflicts[7],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Zeytin Dalı Harekatı\'nda 20 Ocak 2018\'de Afrin\'de şehit olan kahraman astsubay.',
    story:
      '20 Ocak 2018\'de başlayan Zeytin Dalı Harekatı\'nda Afrin bölgesindeki ilk çatışmalarda şehit oldu. Harekatın ilk şehitlerinden olan Musa Özalkan\'ın fedakarlığı, sınır ötesi mücadelemizin sembollerinden oldu.',
    profile_photo_url: null,
    grave_location: 'Kastamonu',
    lat: 41.376,
    lng: 33.778,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h46',
    full_name: 'Ahmet Topçu',
    rank: 'Astsubay Çavuş',
    unit: 'Barış Pınarı Harekatı',
    birth_date: '1993-01-01',
    birth_place: 'Samsun',
    death_date: '2019-10-09',
    death_place: 'Rasulayn, Suriye',
    conflict_id: 'd-8',
    conflict: demoConflicts[7],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Barış Pınarı Harekatı\'nın ilk şehidi; 9 Ekim 2019\'da Rasulayn\'da şehit olan kahraman asker.',
    story:
      '9 Ekim 2019\'da başlatılan Barış Pınarı Harekatı\'nda Rasulayn (Resulayn) bölgesindeki çatışmalarda şehit oldu. Harekatın ilk şehidi olarak tarihe geçti; sınırımızda huzur ve güven için canını verdi.',
    profile_photo_url: null,
    grave_location: 'Samsun',
    lat: 41.286,
    lng: 36.33,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h47',
    full_name: 'Mustafa Muhammed Ak',
    rank: 'Piyade Uzman Çavuş',
    unit: 'Bahar Kalkanı Harekatı',
    birth_date: null,
    birth_place: 'İzmir',
    death_date: '2020-03-03',
    death_place: 'İdlib, Suriye',
    conflict_id: 'd-8',
    conflict: demoConflicts[7],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Bahar Kalkanı Harekatı\'nda 3 Mart 2020\'de İdlib\'de şehit olan İzmirli kahraman asker.',
    story:
      'İdlib\'de başlatılan Bahar Kalkanı Harekatı sırasında görev yaparken rejim güçlerinin saldırısında şehit oldu. İzmir\'in gururu olan Mustafa Muhammed Ak, sınır ötesi operasyonlarımızın kahramanlarındandır.',
    profile_photo_url: null,
    grave_location: 'İzmir',
    lat: 38.419,
    lng: 27.129,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),

  // ============================================================
  // DİĞER (d-9)
  // ============================================================
  hero({
    id: 'd-h5',
    full_name: 'Nene Hatun',
    rank: null,
    unit: 'Aziziye Tabyası Savunması',
    birth_date: '1857-01-01',
    birth_place: 'Erzurum',
    death_date: '1955-05-22',
    death_place: 'Erzurum',
    conflict_id: 'd-9',
    conflict: demoConflicts[8],
    is_martyr: false,
    is_veteran: true,
    summary:
      '93 Harbi\'nde kucağındaki bebeğini bırakıp eline balta alarak Aziziye Tabyası\'nın savunmasına katılan destanlaşan Türk kadını.',
    story:
      '1877-1878 Osmanlı-Rus Savaşı (93 Harbi) sırasında Erzurum Aziziye Tabyası\'nın Rusların eline geçtiğini duyunca bebeğini evde bırakıp eline balta alarak halkın önünde tabyaya koştu. Savunmada büyük kahramanlık gösterdi; 1955\'te "Yılın Annesi" seçildi.',
    profile_photo_url: null,
    grave_location: 'Aziziye Tabyası, Erzurum',
    lat: 39.912,
    lng: 41.254,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
  hero({
    id: 'd-h48',
    full_name: 'Halil Kut',
    rank: 'Mirliva (Tuğgeneral)',
    unit: 'Irak Cephesi Komutanı',
    birth_date: '1881-01-01',
    birth_place: 'İstanbul',
    death_date: '1957-08-27',
    death_place: 'İstanbul',
    conflict_id: 'd-9',
    conflict: demoConflicts[8],
    is_martyr: false,
    is_veteran: true,
    summary:
      '1916\'da Kut-ül Amare\'de İngiliz ordusunu teslim alarak tarihe geçen, "Kut\'un Aslanı" lakabıyla anılan komutan.',
    story:
      'Birinci Dünya Savaşı\'nda Irak Cephesi\'nde 6. Ordu birliklerine komuta etti. 29 Nisan 1916\'da Kut-ül Amare\'de General Townshend komutasındaki İngiliz ordusunu teslim aldı; bu zafer, İngiliz ordusunun tarihindeki en büyük yenilgilerden biri sayılır. 1957\'de İstanbul\'da vefat etti.',
    profile_photo_url: PHOTOS.halilKut,
    grave_location: 'İstanbul',
    lat: 41.008,
    lng: 28.978,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
  }),
];

// ============================================================
// PINNED: SABİT İLK İKİ KAHRAMAN
// Mustafa Kemal Atatürk (d-h2) ve Ömer Halisdemir (d-h6)
// liste ne olursa olsun en üstte kalır.
// ============================================================
export const PINNED_HERO_IDS = ['d-h2', 'd-h6'];

// ============================================================
// MSB ŞEHİT BİLGİ KAPISI: KUDSÜS KAYITLARI (337 kişi, 1877-1918)
// Kaynak: https://www.msb.gov.tr/SehitBilgiKapisi/
// ============================================================
demoHeroes.push(...kudusMartyrs);

// ============================================================
// TSK MEHMETÇİK VAKFI: GÖREV ŞEHİTLERİ (202 kişi, 2014-2025)
// Kaynak: https://www.mehmetcik.org.tr/sehitlerimiz
// ============================================================
demoHeroes.push(...mehmetcikMartyrs);
