import type { Conflict, Hero } from './types';

export function isDemoMode(): boolean {
  return !process.env.EXPO_PUBLIC_SUPABASE_URL;
}

export const demoConflicts: Conflict[] = [
  { id: 'd-1', name: 'Çanakkale Savaşı', sort_order: 10 },
  { id: 'd-2', name: 'Sarıkamış Harekatı', sort_order: 20 },
  { id: 'd-3', name: 'Kurtuluş Savaşı', sort_order: 30 },
  { id: 'd-4', name: 'Kore Savaşı', sort_order: 40 },
  { id: 'd-5', name: 'Kıbrıs Barış Harekatı', sort_order: 50 },
  { id: 'd-6', name: '15 Temmuz Darbe Girişimi', sort_order: 60 },
  { id: 'd-7', name: 'Terörle Mücadele', sort_order: 70 },
  { id: 'd-8', name: 'Sınır Ötesi Operasyonlar', sort_order: 80 },
  { id: 'd-9', name: 'Diğer', sort_order: 90 },
];

const now = new Date().toISOString();

export const demoHeroes: Hero[] = [
  {
    id: 'd-h1',
    full_name: 'Seyit Onbaşı (Seyit Ali Çabuk)',
    rank: 'Onbaşı',
    unit: '27. Alay, Ağır Topçu Bataryası',
    birth_date: '1889-09-01',
    birth_place: 'Balıkesir',
    death_date: '1939-11-30',
    death_place: 'Balıkesir',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Çanakkale Savaşı sırasında 215 kilogramlık top mermisini sırtında taşıyarak İngiliz zırhlısı HMS Ocean\'ı vurmasıyla bilinen efsanevi asker.',
    story:
      '18 Mart 1915\'te Rumeli Mecidiye Tabyası\'nda, topun mermi kaldıran vinci isabet sonucu bozulunca 215 kilogramlık mermiyi sırtında taşıyıp topa sürerek HMS Ocean\'ı kıç tarafından vurdu ve zırhlının batmasına yol açtı. Savaştan sonra memleketi Balıkesir\'e dönen Seyit Onbaşı, 1939\'da vefat etti ve vasiyeti üzerine tabyadaki yeri önüne defnedildi.',
    profile_photo_url: null,
    grave_location: 'Çanakkale, Rumeli Mecidiye Tabyası',
    lat: 40.058,
    lng: 26.183,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h2',
    full_name: 'Mustafa Kemal Atatürk',
    rank: 'Mareşal',
    unit: 'Türk Silahlı Kuvvetleri Başkomutanı',
    birth_date: '1881-01-01',
    birth_place: 'Selanik',
    death_date: '1938-11-10',
    death_place: 'İstanbul',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      'Kurtuluş Savaşı\'nın önderi, Çanakkale\'de "Size taarruzu değil ölmeyi emrediyorum" sözüyle tarihe geçen Türkiye Cumhuriyeti\'nin kurucusu.',
    story:
      'Çanakkale Savaşı\'nda Anafartalar ve Conkbayırı zaferleriyle savaşın seyrini değiştirdi. "Ben size taarruzu değil, ölmeyi emrediyorum!" emriyle 57. Alay\'a ve tüm Mehmetçik\'e cesaret oldu. Kurtuluş Savaşı\'nı başlatarak Türkiye Cumhuriyeti\'ni kurdu.',
    profile_photo_url: null,
    grave_location: 'Anıtkabir, Ankara',
    lat: 39.925,
    lng: 32.837,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h3',
    full_name: 'Yahya Çavuş',
    rank: 'Çavuş',
    unit: 'Seddülbahir, 26. Alay',
    birth_date: '1887-01-01',
    birth_place: 'Balıkesir',
    death_date: '1915-04-25',
    death_place: 'Seddülbahir, Çanakkale',
    conflict_id: 'd-1',
    conflict: demoConflicts[0],
    is_martyr: true,
    is_veteran: false,
    summary:
      '25 Nisan 1915\'te Seddülbahir\'de 10 kişilik mangasıyla bir taburluk Anzak çıkarmasını saatlerce durduran kahraman çavuş.',
    story:
      '25 Nisan 1915 sabahı Seddülbahir kalesinde 10 kişilik ekibiyle düşman çıkarmasına karşı koydu. Ertesi gün şehit olduğunda vücudunda 14 kurşun yarası vardı; fakat o bir gün boyunca Anzak çıkarmasını tek başına durdurmuştu.',
    profile_photo_url: null,
    grave_location: 'Seddülbahir Şehitliği, Çanakkale',
    lat: 40.043,
    lng: 26.159,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h4',
    full_name: 'Şerife Bacı',
    rank: null,
    unit: 'Cephe Gerisi Hizmeti',
    birth_date: '1900-01-01',
    birth_place: 'Kastamonu',
    death_date: '1921-01-01',
    death_place: 'Kastamonu',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Kurtuluş Savaşı\'nda cephane taşırken dondurucu soğukta şehit olan kahraman Türk kadını.',
    story:
      'İnebolu\'dan cepheye cephane taşıyan kağnı kafilesinde kundağındaki bebeğiyle yola çıkan Şerife Bacı, yağmur ve kar altında cephaneyi ıslanmasın diye üstündeki örtüyle örttü. Sabaha karşı donmuş bedeni ve yanında bebeği bulundu; cephane sağlam olarak cepheye ulaşmıştı.',
    profile_photo_url: null,
    grave_location: 'Kastamonu Şehitliği',
    lat: 41.376,
    lng: 33.778,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h5',
    full_name: 'Nene Hatun',
    rank: null,
    unit: 'Aziziye Tabyası Savunması',
    birth_date: '1857-01-01',
    birth_place: 'Erzurum',
    death_date: '1955-05-22',
    death_place: 'Erzurum',
    conflict_id: 'd-3',
    conflict: demoConflicts[2],
    is_martyr: false,
    is_veteran: true,
    summary:
      '93 Harbi\'nde kucağındaki bebeğini bırakıp eline balta alarak Aziziye Tabyası\'nın savunmasına katılan destanlaşan Türk kadını.',
    story:
      '1877-1878 Osmanlı-Rus Savaşı (93 Harbi) sırasında Erzurum Aziziye Tabyası\'nın Rusların eline geçtiğini duyunca bebeğini evde bırakıp eline balta alarak halkın önünde tabyaya koştu. Savunmada büyük kahramanlık gösterdi; 1955\'te "Yılın Annesi" seçildi.',
    profile_photo_url: null,
    grave_location: 'Aziziye Tabyası, Erzurum',
    lat: 39.912,
    lng: 41.254,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h6',
    full_name: 'Ömer Halisdemir',
    rank: 'Piyade Astsubay Kıdemli Başçavuş',
    unit: 'Özel Kuvvetler Komutanlığı',
    birth_date: '1974-02-10',
    birth_place: 'Niğde',
    death_date: '2016-07-16',
    death_place: 'Ankara',
    conflict_id: 'd-6',
    conflict: demoConflicts[5],
    is_martyr: true,
    is_veteran: false,
    summary:
      '15 Temmuz darbe girişiminde darbeci generali vurarak Özel Kuvvetler Komutanlığının ele geçirilmesini engelleyen, ardından şehit edilen kahraman asker.',
    story:
      '15 Temmuz 2016 gecesi darbeci general Semih Terzi\'nin komutanlığı ele geçirmeye çalıştığı sırada, milletinin emriyle hareket ederek Terzi\'yi etkisiz hale getirdi. Bu fedakarlığı Özel Kuvvetler Komutanlığının darbecilerin eline geçmesini engelledi. Hemen ardından şehit edildi. Kabri, şehadetinin yıldönümlerinde binlerce vatandaş tarafından ziyaret edilmektedir.',
    profile_photo_url: null,
    grave_location: 'Niğde, Merkez Mezarlığı',
    lat: 37.969,
    lng: 34.678,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h7',
    full_name: 'Emin Çakıroğlu',
    rank: 'Piyade Teğmen',
    unit: 'Özel Harp Dairesi',
    birth_date: '1979-05-01',
    birth_place: 'İstanbul',
    death_date: '2000-07-25',
    death_place: 'Kırklareli',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      'Devletin içine sızmış olan ihanet şebekesine karşı mücadele ederken 25 Temmuz 2000 gecesi şehit edilen istihbarat subayı.',
    story:
      'Atatürkçülüğe ve milletine sadık bir istihbarat subayı olarak vatan hainlerinin planlarını devlete aktardığı için 2000 yılında şehit edildi. Davası 2022\'de sonuçlandı; aziz hatırası Türk milletinin gönlünde yaşamaktadır.',
    profile_photo_url: null,
    grave_location: 'İstanbul',
    lat: 41.008,
    lng: 28.978,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'd-h8',
    full_name: 'Fethi Sekin',
    rank: 'Komiser Yardımcısı',
    unit: 'İzmir Emniyet Müdürlüğü',
    birth_date: '1962-01-01',
    birth_place: 'Iğdır',
    death_date: '2017-01-05',
    death_place: 'İzmir',
    conflict_id: 'd-7',
    conflict: demoConflicts[6],
    is_martyr: true,
    is_veteran: false,
    summary:
      '5 Ocak 2017\'de İzmir Adliyesi önünde terör saldırısını, silah arkadaşı Musa Can ile birlikte kendi canını feda ederek engelleyen kahraman polis.',
    story:
      '5 Ocak 2017 sabahı İzmir Adliyesi önünde kendini patlatmak üzere olan teröristleri, yanında tek silah arkadaşı Musa Can ile birlikte karşıladı. Göğüs göğüse çatışmada teröristleri etkisiz hale getirdi ve olası yüzlerce canı kurtardı; çatışmada şehit oldu. Silah arkadaşı Komiser Musa Can da şehitler kervanına katıldı.',
    profile_photo_url: null,
    grave_location: 'Iğdır, Ağrıdağı Şehitliği',
    lat: 39.888,
    lng: 44.033,
    status: 'approved',
    rejection_reason: null,
    created_by: null,
    approved_by: null,
    approved_at: now,
    created_at: now,
    updated_at: now,
  },
];
